OPENAI_API_KEY = "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"
SPEECH_KEY = "34372e8d5836409482ccbeec4358ba95"
SPEECH_REGION = "eastus"
aws_secret_access_key = "b60UL0yN1mU3iiPQKvunR3J8K/h/flSlCy7UA1wV"
aws_access_key_id = "AKIATDEYCF7UTWRIFRUC"


