openai.organization = "org-PKfUSNXJSLNqWsYbubAwas81"
OPENAI_API_KEY = "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"
aws_secret_access_key = "b60UL0yN1mU3iiPQKvunR3J8K/h/flSlCy7UA1wV"
aws_access_key_id = "AKIATDEYCF7UTWRIFRUC"